# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode, shape, value=None):
    mode = mode.lower()
    
    if mode == 'zeros':
        # مصفوفة أصفار
        return np.zeros(shape)
    
    elif mode == 'ones':
        # مصفوفة وحايد
        return np.ones(shape)
    
    elif mode == 'full':
        # مصفوفة بقيمة ثابتة (value)
        return np.full(shape, value)
    
    elif mode == 'identity':
        # مصفوفة الوحدة Identity Matrix
        n = shape[0] if isinstance(shape, (tuple, list)) else shape
        return np.eye(n)
    
    else:
        raise ValueError("Unknown mode!")

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [2]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. تحويل المدخلات إلى مصفوفات NumPy.
    2. تغيير شكل المصفوفة الأولى.
    3. دمج المصفوفتين رأسياً.
    """
    try:
        # تحويل المدخلات إلى مصفوفات NumPy لضمان التعامل معها كـ Tensors
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # تغيير شكل arr1 إلى الشكل المطلوب (مثلاً من 1D إلى 2D)
        # ملاحظة: لازم عدد العناصر الكلي يفضل ثابت
        reshaped_arr1 = arr1.reshape(new_shape)

        # دمج المصفوفتين رأسياً (Vertical Stacking)
        # شرط أساسي: لازم يكون ليهم نفس عدد الأعمدة (Columns)
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # التعامل مع أخطاء الحجم أو عدم توافق الأعمدة
        raise ValueError(f"Company-grade Error: {e}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [3]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    البحث عن العناصر التي تحقق الشرط (أكبر من أو يساوي threshold)
    واستبدالها بقيمة جديدة.
    """
    # 1. تحويل المدخل إلى مصفوفة numpy
    arr = np.array(arr)

    # 2. تعريف الشرط: مقارنة كل عنصر بالـ threshold
    # دي هتنتج مصفوفة من القيم المنطقية (True/False)
    condition = (arr >= threshold)
    
    # 3. تعديل المصفوفة باستخدام np.where
    # المنطق: لو الشرط True حط القيمة الجديدة، لو False سيب القيمة الأصلية زي ما هي
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

TestCase

In [ ]:
# بيانات الفرع أ (بيانات مسطحة)
branch_a = [1, 2, 3, 4, 5, 6] 

# بيانات الفرع ب (مصفوفة جاهزة 2x3)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# لاحظ هنا: استخدمنا secure_reshape_and_stack بدلاً من apply_threshold
# لأننا نريد تغيير الشكل (Reshape) ثم الدمج (Stack)
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))

print("التقرير النهائي للمبيعات (4 صفوف × 3 أعمدة):")
print(final_report)
print(f"شكل المصفوفة النهائي: {final_report.shape}")

التقرير النهائي للمبيعات (4 صفوف × 3 أعمدة):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
شكل المصفوفة النهائي: (4, 3)


In [ ]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])